vidyarthi/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('', include('account.urls')),
    path('profile/', include('work.urls', namespace='work')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

work/urls.py
from django.urls import path

from . import views
app_name = 'work'

urlpatterns = [
    
    path('basic_info/',views.basic_info , name = 'profile'),
    path('education/create/',views.education , name = 'education'),
    path('basic_info/education/courses/',views.courses , name = 'courses'),
    path('basic_info/education/courses/docs/',views.other_doc , name = 'other_doc'),
    path('<slug:slug>/', views.profile , name='view_profile'),
]

work/models.py
from django.db import models
from django.contrib.auth.models import User
# from taggit.managers import TaggableManager
from django.core.validators import RegexValidator
from django.urls import reverse
from django.template.defaultfilters import slugify
'''PROFILE'''
from io import BytesIO
from django.core.files.uploadedfile import SimpleUploadedFile
class Profile(models.Model):

    STATUS_CHOICES = (('student','STUDENT'),('employer','EMPLOYER'),('freelancer','FREELANCER'))
    COUNTRY_CHOICES = (('australia','AUSTRALIA'),('india','INDIA'),('united states of america','UNITED STATES OF AMERICA'),('united kingdoms','UNITED KINGDOMS'))
    
    
    user= models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile')
    
    mother_name = models.CharField(max_length = 60, null = True , blank = True)
    fathers_name = models.CharField(max_length = 60 , null= True , blank = True)
    date_of_birth =  models.DateField(null= True ,blank = True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
     message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=12, blank=True)
    state = models.CharField(max_length = 50,default='any')
    city = models.CharField(max_length = 50,default='any')
    area = models.CharField(max_length = 50,default='any')
    country = models.CharField(max_length=50, choices=COUNTRY_CHOICES ,default ='india')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,default='student')
    slug = models.SlugField(max_length=50, null=True, blank=True)
    

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    # def get_absolute_url(self):
    #     reverse('work:view_profile', args=[self.slug])    

class ProfileQRCode(models.Model):
    profile = models.OneToOneField(Profile, related_name='qr_code', on_delete=models.CASCADE, max_length=100,
                                         null=True, blank=True, unique=True)
    qr_code = models.ImageField(upload_to="QR_codes/", null=True, blank=True)
    
    def save(self, *args, **kwargs):
        url = "http://127.0.0.1:8000"
        # store_id = "rqojqQuzumU::" + str(self.store.pk)
        # store_id = base64.urlsafe_b64encode(store_id)
        # print(store_id)
        # self.slug = slugify(str(self.feedback_form))
        sub_url = url + reverse('work:view_profile', args=[self.profile])
        print(sub_url)
        # short_qr_code = self.short_code  = GenerateUrl().qr_shortner(sub_url)
        # print(short_qr_code)
        import qrcode
        qr = qrcode.QRCode(
            version=1,
            box_size=20,
            border=0
        )
        qr.add_data(sub_url)
        qr.make(fit=True)
        img = qr.make_image()
        stream = BytesIO()
        img.save(stream, kind='PNG')
        self.qr_code = SimpleUploadedFile("qr_code.png", stream.getvalue())
        super(ProfileQRCode, self).save(*args, **kwargs)

        def __str__(self):
            return self.profile


'''EDUCATION'''

class Education(models.Model):

    DEGREE_CHOICES = (('10','10'),('12','12'),('diploma','DIPLOMA'),('under graduation','UNDER GRADUATION'),('post graduation','POST GRADUATION'))

    Profile = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='education')
    degree = models.CharField(max_length = 20 ,choices = DEGREE_CHOICES,default = '10', null= True , blank = True)
    branch = models.CharField(max_length = 10 ,null=True,blank = True,default = 'in any')
    roll_number = models.CharField(max_length = 15, null= True , blank = True)
    university = models.CharField(max_length = 50, null= True , blank = True)
    duration = models.CharField(max_length = 4 ,default='in years', null= True , blank = True)
    year_of_passing = models.CharField(max_length=4, null= True , blank = True)
    pencentile = models.CharField(max_length = 4 ,default='in numbers', null= True , blank = True)
    upload_marksheet = models.ImageField(upload_to='users/%y/%m/%d', null= True , blank = True)


''' ADDITIONAL COURSES AND CERTIFICATIONS'''

class Courses(models.Model):

    Profile = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='Courses')
    course_name = models.CharField(max_length = 50, null= True , blank = True)
    institute_name = models.CharField(max_length = 50, null= True , blank = True)
    duration = models.CharField(max_length = 2 ,default='in months', null= True , blank = True)
    validity_of_certification = models.CharField(max_length = 2,default='in years', null= True , blank = True)
    upload_certificate = models.ImageField(upload_to='users/%y/%m/%d', null= True , blank = True)


'''SAMPLE SIGNATURE,THUMB IMPRESSIONS,AND DOCUMENTS'''

class Other_doc(models.Model):

    Profile = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='impressions')
    document_1= models.FileField(upload_to = 'media/',null = True,verbose_name='Document 1',  blank = True)
    document_2= models.FileField(upload_to = 'media/',null = True,verbose_name='Document 2',blank = True)
    document_3= models.FileField(upload_to = 'media/',null = True,verbose_name='Document 3', blank = True)
    document_4= models.FileField(upload_to = 'media/',null = True,verbose_name='Document 4', blank = True)
    document_5= models.FileField(upload_to = 'media/',null = True,verbose_name='Document 5',  blank = True)
    signature = models.ImageField(upload_to = 'media/',null = True,verbose_name='Signature Photo',  blank = True)
    signed_photo = models.ImageField(upload_to = 'media/',null = True,verbose_name='Singed Photo',  blank = True)
    thumb_impression_photo = models.ImageField(upload_to = 'media/',null = True,verbose_name='Thumb Impression Photo',  blank = True)                          

work/forms.py
from django import forms
from .models import Profile,Education,Courses,Other_doc

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('user', 'status','mother_name','fathers_name','date_of_birth','phone_number','country','state','city','area')
        exclude = ('user',)

class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ('__all__')
        exclude = ('Profile',)

class CoursesForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = ('__all__')
        exclude = ('Profile',)

class Other_docForm(forms.ModelForm):
    class Meta:
        model = Other_doc
        fields = ('__all__')
        exclude = ('Profile',)

work/views.py
from django.shortcuts import render, get_object_or_404
from . forms import ProfileForm ,EducationForm,CoursesForm,Other_docForm
from django.contrib.auth.models import User
from .models import *
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Profile, ProfileQRCode

def profile(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    qrcode, created = ProfileQRCode.objects.get_or_create(profile=profile)   

    return render(request,'pages/view_profile.html',{'profile':profile
                                                    ,'qrcode':qrcode})

@login_required   
def basic_info(request):
    
    if request.method == 'POST':
        input_form = ProfileForm(data=request.POST, instance=request.user.profile, files=request.FILES)
        if input_form.is_valid():
            input_form.save()
           
    else:
        input_form = ProfileForm(instance=request.user.profile)

    return render(request,'pages/basic.html',{'input_form':input_form})

@login_required
def education(request):
    new_user = request.user
    profile = Profile.objects.get(user=new_user.pk)
    edu, created = Education.objects.get_or_create(Profile=profile)
    if request.method =='POST':
      education_form = EducationForm(data=request.POST, instance=edu, files=request.FILES)
      if education_form.is_valid():
        education_form.save()
      # return HttpResponse('Education updated successfully!')    
    else:
      education_form = EducationForm(instance=edu)
    return render(request,'pages/education.html',{'education_form':education_form})

@login_required        
def courses(request):
    new_user = request.user
    profile = Profile.objects.get(user=new_user.pk)
    cour, created = Courses.objects.get_or_create(Profile=profile)
    if request.method == 'POST':
      couses_form = CoursesForm(request.POST, instance=cour , files=request.FILES)    
      if couses_form.is_valid():
        couses_form.save()
 
    else:
        couses_form = CoursesForm(instance=cour)
    return render(request,'pages/courses.html',{'couses_form':couses_form})

@login_required
def other_doc(request):
    user = request.user
    profile = Profile.objects.get(user=user.pk)
    doc, created = Other_doc.objects.get_or_create(Profile=profile)
    if request.method == 'POST':
      doc_form = Other_docForm(request.POST,  instance=doc, files=request.FILES)
      if doc_form.is_valid():
        doc_form.save()
         
    else:
      doc_form = Other_docForm(instance=doc)
    return render(request,'pages/doc.html',{'doc_form':doc_form})

work/templates/pages/basic.html
{% extends 'base.html' %}
{% load static%}

{% block title%}Profile{% endblock%}
{% block content %}
<div class="card-panel teal lighten-2">
    <h4 class="center white-text">Edit your Profile </h4>
  </div>
  <div class="card-panel">
      <form action="." method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ input_form.as_p }}
    <div class="center">
      <input  type="submit" value="SAVE CHANGES" class="btn-large waves-effect waves-light  z-depth-5">
    </div>
      </form>
  </div>


{% endblock %}

work/templates/pages/complete.html
{% extends 'base.html' %}
{% load static%}
{% block title %} COMPLETE {% endblock %}
{%  block content%}
<h1>YOU HAVE COMPLETED YOUR REGISTRATION NOW YOU CAN GENRATE THE QR CODE OF YOUR PROFILE</h1>
<p><input type="submit" value="GENRATE QR CODE"></p>
{% endblock %}

work/templates/pages/courses.html
{% extends 'base.html' %}
{% load static%}

{% block title%}COURSES{% endblock%}
{% block content %}
<div class="card-panel teal lighten-2">
    <h4 class="center white-text">Edit your Course </h4>
  </div>
  <div class="card-panel">
      <form action="." method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ couses_form.as_p }}
    <div class="center">
      <input  type="submit" value="SAVE CHANGES" class="btn-large waves-effect waves-light  z-depth-5">
    </div>
      </form>
  </div>


{% endblock %}

work/templates/pages/doc.html
{% extends 'base.html' %}
{% load static%}

{% block title %}DOCUMENTS {% endblock %}
{% block content %}
<div class="card-panel teal lighten-2">
    <h4 class="center white-text">Edit your Other Docs </h4>
  </div>
  <div class="card-panel">
      <form action="." method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ doc_form.as_p }}
    <div class="center">
      <input  type="submit" value="SAVE CHANGES" class="btn-large waves-effect waves-light  z-depth-5">
    </div>
      </form>
  </div>


{% endblock %}

work/templates/pages/education.html
{% extends 'base.html' %}
{% load static%}

{% block title%}education{% endblock %}
{% block content%}

<div class="card-panel teal lighten-2">
    <h4 class="center white-text">Edit your Education </h4>
  </div>
  <div class="card-panel">
      <form action="." method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ education_form.as_p }}

    <div class="center">
      <input  type="submit" value="SAVE CHANGES" class="btn-large waves-effect waves-light  z-depth-5">
    </div>
      </form>
  </div>

{% endblock %}

  

work/templates/pages/view_profile.html
{% extends 'base.html' %}
{%load staticfiles%}

{% block content %}
<div class="card-panel teal lighten-2">
    <h4 class="center white-text">WELCOME TO YOUR DASHBOARD HERE YOU CAN ACCESS YOUR PROFILE</h4>
  </div>




  <div class="col s12 m12">
    <h2 class="header cyan-text"><!-- <i>{{ user.first_name }} {{ user.last_name }}</i> --></h2>
    <div class="card horizontal">
      <div class="card-image">
        <img src="{{ qrcode.qr_code.url }}" height="150" width="150">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <h4 class="cyan-text" style="text-align:right;"><i>{{ user.first_name }} {{ user.last_name }}</i></h4>
        </div>
        
      </div>
    </div>
  </div>
         
<hr>







 <div class="card-panel">
  {% if request.user.is_authenticated %}
        <h4><a href="{% url 'work:profile' %}">Complete Your Profile</a></h4>
   {% endif %}     
</div>

       <div class="card-panel">
        {% if request.user.is_authenticated %}
        <h4><a href="{% url 'work:education' %}">EDUCATION</a></h4>
        {% endif %}   
      </div>

      <div class="card-panel">
        {% if request.user.is_authenticated %}
        <h4><a href="{% url 'work:courses' %}">COURCES</a></h4>
        {% endif %}   
    </div>

      <div class="card-panel">
        {% if request.user.is_authenticated %}
        <h4><a href="{% url 'work:other_doc'%}">OTHER DOCUMENTS</a></h4>
        {% endif %}   
      </div>

  

{% endblock %}